export { default as Layout } from './layout/layout';
export { default as Loader } from './Loader/loader';
export { default as Navbar } from './layout/Navbar/navbar';
export { default as PokemonCard } from './PokemonCard';
export { default as PokemonType } from './PokemonType';
export { default as PokemonStats } from './PokemonStats';
export { default as PokemonEvolutions } from './PokemonEvolutions/pokemonEvolutions';
export { default as EvolutionGen } from './PokemonEvolutions/EvolutionGen/evolutionGen';
export { default as ImageResource } from './ImageResource';